# 共通クライアントペルソナスキーマ
type: object
required:
  - id
  - business_goal
  - domain
  - budget_level
  - risk_tolerance
  - decision_style
  - communication_style
  - success_criteria
  - anti_patterns
properties:
  id:
    type: string
    description: "ペルソナID。snake_case推奨"
  business_goal:
    type: string
    description: "最上位の事業目標"
  domain:
    type: string
    description: "所属業界または職能"
  budget_level:
    type: string
    enum: [low, mid, high, low-mid, mid-high]
    description: "プロジェクトに割ける予算感（ハイブリッド表現も可: low-mid, mid-high など）"
  risk_tolerance:
    type: string
    enum: [low, mid, high, unpredictable]
    description: "不確実性をどれだけ許容できるか（予測困難な場合は unpredictable を使用）"
  decision_style:
    type: string
    description: "意思決定プロセス（例: data-driven, consensus, top-down, 合議制, ワンマン, 現場丸投げ など）"
  communication_style:
    type: string
    description: "好まれるコミュニケーション方法（例: async-detailed, sync-brief, ロジカルで淡々, 感情重視で共感優先, テンション高めのハイコンテクスト など）"
  success_criteria:
    type: array
    items:
      type: string
    minItems: 1
    description: "成功を測定する指標や条件"
  anti_patterns:
    type: array
    items:
      type: string
    minItems: 1
    description: "避けるべき行動・意思決定パターン"
